name: devops-task

on: 
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: py-install
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install dependencies
        run: pip install -r app/requirements.txt

      - name: install pytest
        run: pip install pytest

      - name: pytest
        run: pytest 


