name: devops-task

on: 
  push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: py-install
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install dependencies
        run: pip install -r app/requirements.txt

      - name: install pytest
        run: pip install pytest

      - name: pytest
        run: PYTHONPATH=. pytest 
        
      - name: docker build
        run: |
          docker build -t arturasryan/devops-revision-app:1.0 .
          docker tag arturasryan/devops-revision-app:1.0 arturasryan/devops-revision-app:latest
      - name: docker run
        run: |
          docker run -d --name devops-app -p 5000:5000 arturasryan/devops-revision-app:latest

      - name: waiting healthy status
        run: |
           while [ "$(docker inspect --format='{{.State.Health.Status}}' devops-app)" != "healthy" ]; do
           echo "Waiting for container to become healthy..."
           sleep 2
          done
          echo "Container is healthy!"

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker push
        run: docker push arturasryan/devops-revision-app:latest


  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: after ci
        run: |
          docker compose pull
          docker compose up -d

      - name: docker healthyy check 
        run: |
          while [ "$(docker inspect --format='{{.State.Health.Status}}' devopspractical-app-1)" != "healthy" ]; do
            echo "Waiting for container to become healthy..."
            sleep 2
          done
          echo "Container is healthy!"
      - name: checking health app
        run: curl localhost:5000/health
